version: '3'
services:
   mystok-app:
      build: ./mystok-app 
      image: mystok-app:3
      ports:
       - 18080:8080
      volumes:
      - ./mystok-app/webapps:/usr/local/tomcat/webapps/
      depends_on:
        - mystok-db
   mystok-db:
      image: dekabitasp/mystok-mysql-search-japanese-test:solved
